version: "3.9"

# ----------------------------------------------------------------------------
# Services
# ----------------------------------------------------------------------------
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app